### PR TITLE
Add basename option

### PR DESCRIPTION
**Pull request by Cefold**
* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] The changes are appropriately documented (if applicable).
* [x] The changes have sufficient test coverage (if applicable).
* [x] The testsuite passes successfully on my local machine (if applicable).

**Summarize your changes:**
Add basename option to `generateFinalBasename`, that we could avoid [this error](https://github.com/nodejs/node-gyp/issues/65) if the appname has space.

### CODE REVIEW

**Review by malept — COMMENTED** [review]
I think there are better solutions for this problem than adding **yet another** confusing option to Packager, but I'll let other Ecosystem WG members weigh in.

**Comment by Cefold** [comment]
> I think there are better solutions for this problem than adding **yet another** confusing option to Packager, but I'll let other Ecosystem WG members weigh in.

We could also try this: `${sanitizeAppName(opts.name.replace(' ', ''))}-${opts.platform}-${opts.arch}`

**Comment by malept** [comment]
Regardless of the implementation,  it'd be best if you added tests which showed what the intended behavior is supposed to be.

**Comment by Cefold** [comment]
Any recommendation from WG-ecosystem?

**Comment by felixrieseberg** [comment]
I _just_ came across this problem, too. This solution here would fix my problem.

The real problem is that `electron-packager` lets you disable the use of `tmpdir` but doesn't let you control what the folder is named it'll use to package. I'd love to override the folder name.

@malept I think I'm generally in favor of merging it in.

**Comment by malept** [comment]
>  have it use name over productName for the folder naming.

I'd be more inclined to do this than add another flag, but I currently lack the context of what might break if we did that.

**Comment by felixrieseberg** [comment]
In theory, the internal folder structure is an implementation detail and not part of the API, so we _could_ change it in a minor version.

**Comment by felixrieseberg** [comment]
I'd love to fix this problem! I tried a few things here and I believe that changing how we generate the name is the best thing we can do, because _either_ solution will require a change in `electron-forge`. 

I'm closing this PR here. @Cefold I am so sorry about how long it took for us to actually act here.

**Pull request closed without merging**
